# Generated by Django 3.1.2 on 2020-11-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('due_date', models.DateField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('title', 'due_date')},
            },
        ),
    ]
