# Generated by Django 3.1.2 on 2020-10-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('name', 'due_date')},
            },
        ),
    ]
